"""NSML Example (Autogenerated name.)
=====================================


Please edit this text to describe what this file does. It is included
automatically in the documentation.

"""

from distutils.core import setup
setup(name='hello_nsml', version='1.0')
